### ISSUE TITLE
Turning hwid to variable outside gethwid function

### ISSUE THREAD

**Issue by NotII** [luludotdev/hwid#1]
Im pretty stupid but how would i turn the id into a variable that i can use outside the gethwid function

**Comment by luludotdev** [comment]
I'm not sure I understand the question

**Comment by ghost** [comment]
im not familiar with anonymous functions and have the same question.

getHWID().then(id => {
  // use ID however you want
})

im having a hard time using 'id' outside of this anonymous functions scope, id like to return it or assign it something I can use elsewhere in the program. thanks.

**Comment by elmcapp** [comment]
getHWID().then(id => {
// use ID however you want
console.log('your hardware ID is:', id)
})

or

const otherFunction =(hwid)=>{
   // what ever you want to do with the id
}

getHWID().then(id => {
    otherFunction(id)
})

**Comment by ghost** [comment]
thanks for the tip, appreciate it!

**Comment by luludotdev** [comment]
`getHWID()` runs asynchronously and as such returns a [Promise](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise). You can use this promise directly or you can use it as part of [async/await](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/async_function) code.
