### ISSUE TITLE
Support CommonJS?

### ISSUE THREAD

**Issue by sleeyax** [luludotdev/hwid#4]
It's not possible to import your package from a codebase that's using CommonJS `require()` syntax. 

A simple `const { getHWID } = require('hwid')` results in `Error [ERR_REQUIRE_ESM]: Must use import to load ES Module`.

Do you plan to support it in any way?

Thanks

**Comment by luludotdev** [comment]
CommonJS support is available on v0.3.0 or older. I do not plan to re-add support in order to push the Node.js ecosystem forwards. See [this post](https://gist.github.com/sindresorhus/a39789f98801d908bbc7ff3ecc99d99c) for more information.
